
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exp11(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [31:0] PC;

rv32_ctrl(
	.clock(KEY[1]),
	.reset(KEY[0]),
	.debugdata(PC)
);

bcd7seg seg0(PC[3:0], HEX0);
bcd7seg seg1(PC[7:4], HEX1);
bcd7seg seg2(PC[11:8], HEX2);
bcd7seg seg3(PC[15:12], HEX3);
bcd7seg seg4(PC[19:16], HEX4);
bcd7seg seg5(PC[23:20], HEX5);

//=======================================================
//  Structural coding
//=======================================================



endmodule
